name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v4
      # - run: sudo apt install cowsay -y
      # - run: ls -l
      - run: cat README.md | cowsay
