name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    # container:
    #   image: ghcr.io/cicd-lectures/gitpod:latest
    #   options: --user=root
    steps:
      - uses: actions/checkout@v4
      - uses: juliangruber/read-file-action@v1
        id: readfile
        with:
          path: ./README.md
      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: "${{ steps.readfile.outputs.content }}"
          cow: 'random'
